/**
 * MGM R numerical equivalence tests
 *
 * Compares our fitMGM() against R's mgm::mgm()
 * using identical input data generated by generate-mgm-ground-truth.R.
 *
 * Key differences from R's mgm:
 *   - R's mgm uses glmnet internally with its own lambda path/scaling
 *   - R's mgm type "c" for binary uses multinomial logistic; we use binomial
 *   - Edge weight computation may differ in normalization
 *
 * Tolerances:
 *   - Structure (nonzero edges): allow at most 2 disagreements per dataset
 *   - Edge weights: compared on shared edges only
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { fitMGM } from '../../src/estimation/mgm';
import type { MgmNodeType } from '../../src/core/types';

// ── Load R ground truth ──
interface RMgmDataset {
  data: Record<string, number[]>;
  n: number;
  p: number;
  labels: string[];
  types: string[];
  levels: number[];
  weightMatrix: number[][];
  signMatrix: number[][];
}

interface RMgmGroundTruth {
  dataset1_all_gaussian: RMgmDataset;
  dataset2_all_binary: RMgmDataset;
  dataset3_mixed: RMgmDataset;
}

const gtPath = join(__dirname, '..', 'fixtures', 'mgm-ground-truth.json');
const gt: RMgmGroundTruth = JSON.parse(readFileSync(gtPath, 'utf-8'));

function columnsToRows(data: Record<string, number[]>, labels: string[]): number[][] {
  const n = data[labels[0]!]!.length;
  return Array.from({ length: n }, (_, i) =>
    labels.map(label => data[label]![i]!),
  );
}

function rTypeToNodeType(rType: string): MgmNodeType {
  if (rType === 'g') return 'gaussian';
  if (rType === 'c') return 'binary';
  if (rType === 'p') return 'poisson';
  throw new Error(`Unknown R type: ${rType}`);
}

function countEdges(matrix: number[][], threshold = 1e-6): number {
  let count = 0;
  const p = matrix.length;
  for (let i = 0; i < p; i++) {
    for (let j = i + 1; j < p; j++) {
      if (Math.abs(matrix[i]![j]!) > threshold) count++;
    }
  }
  return count;
}

function getEdgeStructure(matrix: number[][], threshold = 1e-6): boolean[][] {
  const p = matrix.length;
  return Array.from({ length: p }, (_, i) =>
    Array.from({ length: p }, (_, j) => Math.abs(matrix[i]![j]!) > threshold),
  );
}

// ═══════════════════════════════════════════════════════════
//  Dataset 1: All-gaussian (p=4, n=300)
// ═══════════════════════════════════════════════════════════

describe('MGM R equivalence — Dataset 1 (all-gaussian, n=300, p=4)', () => {
  const ds = gt.dataset1_all_gaussian;
  const data = columnsToRows(ds.data, ds.labels);
  const nodeTypes = ds.types.map(rTypeToNodeType);
  const result = fitMGM(data, ds.labels, nodeTypes, { gamma: 0.25, rule: 'AND' });

  it('edge count within ±3 of R', () => {
    const rEdges = countEdges(ds.weightMatrix);
    const jsEdges = countEdges(result.weightMatrix);
    console.log(`  all-gaussian: R edges=${rEdges}, JS edges=${jsEdges}`);
    expect(Math.abs(rEdges - jsEdges)).toBeLessThanOrEqual(3);
  });

  it('structure matches R (at most 2 disagreements)', () => {
    const rStruct = getEdgeStructure(ds.weightMatrix);
    const jsStruct = getEdgeStructure(result.weightMatrix);
    let mismatches = 0;
    for (let i = 0; i < ds.p; i++) {
      for (let j = i + 1; j < ds.p; j++) {
        if (rStruct[i]![j] !== jsStruct[i]![j]) mismatches++;
      }
    }
    expect(mismatches).toBeLessThanOrEqual(2);
  });

  it('symmetric weight matrix with zero diagonal', () => {
    for (let i = 0; i < ds.p; i++) {
      expect(result.weightMatrix[i]![i]).toBe(0);
      for (let j = i + 1; j < ds.p; j++) {
        expect(result.weightMatrix[i]![j]).toBeCloseTo(result.weightMatrix[j]![i]!, 10);
      }
    }
  });

  it('shared edges have similar weights', () => {
    let maxDiff = 0;
    let compared = 0;
    for (let i = 0; i < ds.p; i++) {
      for (let j = i + 1; j < ds.p; j++) {
        const rw = ds.weightMatrix[i]![j]!;
        const jsw = result.weightMatrix[i]![j]!;
        if (rw > 0.01 && jsw > 0.01) {
          maxDiff = Math.max(maxDiff, Math.abs(rw - jsw));
          compared++;
        }
      }
    }
    console.log(`  shared edges compared: ${compared}, maxDiff: ${maxDiff.toFixed(4)}`);
    // Tolerance is generous due to different glmnet internals
    if (compared > 0) {
      expect(maxDiff).toBeLessThan(0.5);
    }
  });
});

// ═══════════════════════════════════════════════════════════
//  Dataset 2: All-binary (p=4, n=400, chain)
// ═══════════════════════════════════════════════════════════

describe('MGM R equivalence — Dataset 2 (all-binary, n=400, p=4)', () => {
  const ds = gt.dataset2_all_binary;
  const data = columnsToRows(ds.data, ds.labels);
  const nodeTypes = ds.types.map(rTypeToNodeType);
  const result = fitMGM(data, ds.labels, nodeTypes, { gamma: 0.25, rule: 'AND' });

  it('edge count within ±2 of R', () => {
    const rEdges = countEdges(ds.weightMatrix);
    const jsEdges = countEdges(result.weightMatrix);
    console.log(`  all-binary: R edges=${rEdges}, JS edges=${jsEdges}`);
    expect(Math.abs(rEdges - jsEdges)).toBeLessThanOrEqual(2);
  });

  it('structure matches R (at most 1 disagreement)', () => {
    const rStruct = getEdgeStructure(ds.weightMatrix);
    const jsStruct = getEdgeStructure(result.weightMatrix);
    let mismatches = 0;
    for (let i = 0; i < ds.p; i++) {
      for (let j = i + 1; j < ds.p; j++) {
        if (rStruct[i]![j] !== jsStruct[i]![j]) mismatches++;
      }
    }
    expect(mismatches).toBeLessThanOrEqual(1);
  });

  it('chain structure recovered (adjacent > non-adjacent)', () => {
    // R shows clear chain: 1-2, 2-3, 3-4
    const rAdj01 = ds.weightMatrix[0]![1]!;
    const rNonAdj03 = ds.weightMatrix[0]![3]!;
    expect(rAdj01).toBeGreaterThan(rNonAdj03);

    // Our result should show similar pattern
    const jsAdj01 = result.weightMatrix[0]![1]!;
    const jsNonAdj03 = result.weightMatrix[0]![3]!;
    expect(jsAdj01).toBeGreaterThan(jsNonAdj03);
  });

  it('shared edges have similar weights', () => {
    let maxDiff = 0;
    let compared = 0;
    for (let i = 0; i < ds.p; i++) {
      for (let j = i + 1; j < ds.p; j++) {
        const rw = ds.weightMatrix[i]![j]!;
        const jsw = result.weightMatrix[i]![j]!;
        if (rw > 0.01 && jsw > 0.01) {
          maxDiff = Math.max(maxDiff, Math.abs(rw - jsw));
          compared++;
        }
      }
    }
    console.log(`  shared edges compared: ${compared}, maxDiff: ${maxDiff.toFixed(4)}`);
    if (compared > 0) {
      expect(maxDiff).toBeLessThan(0.6);
    }
  });
});

// ═══════════════════════════════════════════════════════════
//  Dataset 3: Mixed data (2 gaussian + 2 binary + 1 poisson)
// ═══════════════════════════════════════════════════════════

describe('MGM R equivalence — Dataset 3 (mixed, n=500, p=5)', () => {
  const ds = gt.dataset3_mixed;
  const data = columnsToRows(ds.data, ds.labels);
  const nodeTypes = ds.types.map(rTypeToNodeType);
  const result = fitMGM(data, ds.labels, nodeTypes, { gamma: 0.25, rule: 'AND' });

  it('edge count within ±3 of R', () => {
    const rEdges = countEdges(ds.weightMatrix);
    const jsEdges = countEdges(result.weightMatrix);
    console.log(`  mixed: R edges=${rEdges}, JS edges=${jsEdges}`);
    expect(Math.abs(rEdges - jsEdges)).toBeLessThanOrEqual(3);
  });

  it('detects gauss1-gauss2 edge (both R and JS)', () => {
    // R shows gauss1-gauss2 = 0.5119
    expect(ds.weightMatrix[0]![1]).toBeGreaterThan(0.1);
    // We should also detect it
    expect(result.weightMatrix[0]![1]).toBeGreaterThan(0);
  });

  it('binary2 (independent) has few edges in both R and JS', () => {
    // R shows binary2 has 0 edges
    const rBinary2Edges = ds.labels.reduce((count, _, j) =>
      j !== 3 && Math.abs(ds.weightMatrix[3]![j]!) > 0.01 ? count + 1 : count, 0);
    expect(rBinary2Edges).toBe(0);

    // Our result should also show few/no edges for binary2
    const jsBinary2Edges = ds.labels.reduce((count, _, j) =>
      j !== 3 && Math.abs(result.weightMatrix[3]![j]!) > 0.01 ? count + 1 : count, 0);
    expect(jsBinary2Edges).toBeLessThanOrEqual(2);
  });

  it('symmetric weight and sign matrices', () => {
    const p = ds.p;
    for (let i = 0; i < p; i++) {
      expect(result.weightMatrix[i]![i]).toBe(0);
      for (let j = i + 1; j < p; j++) {
        expect(result.weightMatrix[i]![j]).toBeCloseTo(result.weightMatrix[j]![i]!, 10);
        expect(result.signMatrix[i]![j]).toBe(result.signMatrix[j]![i]);
      }
    }
  });
});

// ═══════════════════════════════════════════════════════════
//  Summary
// ═══════════════════════════════════════════════════════════

describe('MGM R equivalence — summary', () => {
  it('prints comparison summary', () => {
    const datasets: { name: string; ds: RMgmDataset }[] = [
      { name: 'all-gaussian', ds: gt.dataset1_all_gaussian },
      { name: 'all-binary', ds: gt.dataset2_all_binary },
      { name: 'mixed', ds: gt.dataset3_mixed },
    ];

    for (const { name, ds } of datasets) {
      const data = columnsToRows(ds.data, ds.labels);
      const nodeTypes = ds.types.map(rTypeToNodeType);
      const result = fitMGM(data, ds.labels, nodeTypes, { gamma: 0.25, rule: 'AND' });

      const rEdges = countEdges(ds.weightMatrix);
      const jsEdges = countEdges(result.weightMatrix);

      let maxDiff = 0;
      let sumDiff = 0;
      let count = 0;
      for (let i = 0; i < ds.p; i++) {
        for (let j = i + 1; j < ds.p; j++) {
          const diff = Math.abs(ds.weightMatrix[i]![j]! - result.weightMatrix[i]![j]!);
          if (diff > maxDiff) maxDiff = diff;
          sumDiff += diff;
          count++;
        }
      }

      const structMismatch = (() => {
        const rS = getEdgeStructure(ds.weightMatrix);
        const jsS = getEdgeStructure(result.weightMatrix);
        let m = 0;
        for (let i = 0; i < ds.p; i++) {
          for (let j = i + 1; j < ds.p; j++) {
            if (rS[i]![j] !== jsS[i]![j]) m++;
          }
        }
        return m;
      })();

      console.log(`  ${name}: R edges=${rEdges}, JS edges=${jsEdges}, structMismatch=${structMismatch}, maxDiff=${maxDiff.toFixed(4)}, meanDiff=${(sumDiff / count).toFixed(4)}`);
    }
  });
});
